//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Data.Resources.OrderResources", typeof(OrderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string EntityPlural {
            get {
                return ResourceManager.GetString("EntityPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string EntitySingular {
            get {
                return ResourceManager.GetString("EntitySingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Id.
        /// </summary>
        public static string PropertyCustomerId {
            get {
                return ResourceManager.GetString("PropertyCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Id.
        /// </summary>
        public static string PropertyEmployeeId {
            get {
                return ResourceManager.GetString("PropertyEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight.
        /// </summary>
        public static string PropertyFreight {
            get {
                return ResourceManager.GetString("PropertyFreight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string PropertyOrderDate {
            get {
                return ResourceManager.GetString("PropertyOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        public static string PropertyOrderId {
            get {
                return ResourceManager.GetString("PropertyOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Date.
        /// </summary>
        public static string PropertyRequiredDate {
            get {
                return ResourceManager.GetString("PropertyRequiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Address.
        /// </summary>
        public static string PropertyShipAddress {
            get {
                return ResourceManager.GetString("PropertyShipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship City.
        /// </summary>
        public static string PropertyShipCity {
            get {
                return ResourceManager.GetString("PropertyShipCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Country.
        /// </summary>
        public static string PropertyShipCountry {
            get {
                return ResourceManager.GetString("PropertyShipCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Name.
        /// </summary>
        public static string PropertyShipName {
            get {
                return ResourceManager.GetString("PropertyShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Date.
        /// </summary>
        public static string PropertyShippedDate {
            get {
                return ResourceManager.GetString("PropertyShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Postal Code.
        /// </summary>
        public static string PropertyShipPostalCode {
            get {
                return ResourceManager.GetString("PropertyShipPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Region.
        /// </summary>
        public static string PropertyShipRegion {
            get {
                return ResourceManager.GetString("PropertyShipRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Via.
        /// </summary>
        public static string PropertyShipVia {
            get {
                return ResourceManager.GetString("PropertyShipVia", resourceCulture);
            }
        }
    }
}
